### ISSUE TITLE
ts-loader

### ISSUE THREAD

**Issue by vok123** [luckyyyyy/vue-webpack-ssr#8]
不使用ts-loader应该会更快些

**Comment by luckyyyyy** [comment]
老了 现在可以去掉了 没有时间做更新和验证



发自我的iPhone


------------------ Original ------------------

**Comment by luckyyyyy** [comment]
今天想起这个事 更新了一版 ts-loader还是不能去 随手加了点性能提升的
vue-cli也是这么做的

**Comment by vok123** [comment]
是不是因为 .vue 文件的 ts 代码无法脱离 ts-loader ?

**Comment by luckyyyyy** [comment]
不是的，去掉后缺少了实时检查这个不算影响，最影响的是babel 无法区分引入的是不是类型，如果模块类型混着一起引入就会报不存在，而且反射还需要依赖插件。



发自我的iPhone


------------------ Original ------------------
